### PR TITLE
Fix arm64e crash report text formatting

### LINKED ISSUE #20: arm64e stack trace displays ???
I integrated the latest CrashReporter.framework for iOS available from release 1.2.3-rc1, but the stack trace from an arm64e (iPhone XS) device still display ??? for library names and the addresses are 0. I thought this fork supports arm64e devices. Am I missing something here? Thanks.

### PR DESCRIPTION
**Pull request by MatkovIvan**
Fixes #20
AB#74115

### CODE REVIEW

File: Source/PLCrashReportTextFormatter.m [hunk 1]
```diff
@@ -34,6 +34,11 @@
 #import "PLCrashReportTextFormatter.h"
 #import "PLCrashCompatConstants.h"
 
+// Fix for old XCodes
```
Comment (clpolet) [inline Source/PLCrashReportTextFormatter.m]: Would ti make sense to move this to the `PLCrashCompatConstats.h` file?
